version = 1

test_patterns = ["**/test/**"]

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  module_system = "es-modules"
  environment = [
    "browser",
    "jest"
  ]
  dialect = "typescript"

[[transformers]]
name = "prettier"
enabled = true 
