name: 🍰 Suggest enhancement
description: Suggestions for shifty
title: "Enhancement: <title>"
assignees: shivam-deepsource
labels: [Feature Request, Needs Triage]

body:
  - type: markdown
    attributes:
      label: Describe the enhancement
      value: "> Explain in a few short lines what is the feature you wish to see in this project"

  - type: markdown
    attributes:
      label: How will this enhancement improve the quality of functionality for the library
      value: "> How will this enhancement improve the quality of functionality for the library"
  - type: dropdown
    attributes:
      label: Is this going to be a breaking change
      options:
        - Yes
        - No
